### ISSUE TITLE
Your website is NOT secure and can be Hacked

### ISSUE THREAD

**Issue by ayumihamsaki** [bancorprotocol/contracts#180]
Hello,

I think you must not be aware but your website is delivering Mixed Content and giving somethings HTTP and HTTPs, therefore very easy to hack your website.

Example files that you are delivering via HTTP:

`http://www.bancor.network/static/fonts/333d8c_1_unhinted_0.woff`

See picture how many things are not secure: (All Links in Red)

![untitled](https://user-images.githubusercontent.com/17784082/31177632-850e3adc-a90e-11e7-9875-340458f4fa5f.png)

**Comment by yudilevi** [comment]
We're aware that we're serving mixed content but how does that have anything to do with being able to hack the website?

**Comment by miohtama** [comment]
The issue is correct, headline is sensational so here comes my social disclaimer.

When you enter to crypto business, you'll get all this kind of fake security researchers claiming vulnerabilities and they trying to sell you something or extort money from you. The best approach is to ignore them and ban them. Open a bounty program on a reputable whitehacker service site that do their internal filtering of low quality security researcher contact request.

**Comment by yudilevi** [comment]
We run our own bounty program that also includes security issues so I agree.
Thanks @miohtama :)
