### ISSUE TITLE
Huge exchange threat!!!

### ISSUE THREAD

**Issue by osgee** [bancorprotocol/contracts#19]
In the beginning, the reserved Ethers is 300000\*0.2=60000, BNT supply is 30000000BNT
the current price is 0.01ETH/BNT, BNT cap is 30000000BNT\*0.01ETH/BNT=300000ETH

If some guy has 1000000BNT and 0ETH,  just sales 1000000BNT and get 10000ETH
the price down to (60000-10000)/((30000000-1000000)\*0.2)=0.00862ETH/BNT, now the reserved Ethers is 300000\*0.2-10000=50000, BNT supply is 29000000BNT, BNT cap is 29000000BNT\*0.00862ETH/BNT=249979ETH

and as soon as possible, the same guy buy 1100000BNT @ 0.00862ETH/BNT
the price up to (50000+1100000\*0.00862)/((29000000+1100000)\*0.2)=0.0098ETH/BNT, 
now this guy has 1100000BNT (~10868ETH) and 518ETH, earned 868+518=1386ETH for a round, and he can keep manipulating the BNT contract.

After round 1, BNT supply is 30100000BNT, the BNT cap is 30100000BNT\*0.0098ETH/BNT=294980ETH, which is less than original even there are more BNT issued.

All in all,  this guy drains up the value from BNT network round by round by diluting the BNT!!!

**Comment by osgee** [comment]
@yudilevi @holiman @Arachnid @or2008 @barakman 
I do not know have you guys already restricted the amount of exchange??

**Comment by yudilevi** [comment]
Hey - I'm not sure I'm following you - did you use the bancor formula to calculate the sale return?
The price isn't constant - it's a continuous function, so that for each BNT that the user sells, he/she will get less and less ETH, so it's not as if the entire transaction is done for 0.01, but that's only the starting price.

**Comment by osgee** [comment]
So, you mean you have already split the whole exchange to minor one as 1BNT?

**Comment by yudilevi** [comment]
In essence, that's what the formula does - selling 100 BNTs is like executing 100x1 BNT sale transactions (ignoring the decimals for simplification).

**Comment by osgee** [comment]
Would you please show me the code that deals with the continues change for a exchange?

**Comment by yudilevi** [comment]
Sure, it's all inside BancorFormula -
https://github.com/bancorprotocol/contracts/blob/master/solidity/contracts/BancorFormula.sol

Which is the implementation of the formula from the whitepaper (available on the bancor.network website).

**Comment by holiman** [comment]
The implementation of 'split the whole exchange' is done as an integral, so what the actual code does is calculate that integral which is laid out in the whitepaper.

**Comment by osgee** [comment]
Yes, I have reviewed that. You guys are professional!

**Comment by osgee** [comment]
But have you tested the return amount of huge selling and buying is the same?

**Comment by yudilevi** [comment]
Yes we have, and to prevent any exploits, and since there is always some level of precision loss, it's actually not exactly the same - the user will get almost what he/she is supposed to get - the remaining fraction stays in the reserve for the benefit of all token holders.

**Comment by osgee** [comment]
Anyway, we still can not prevent big investors to manipulate the market by pull up the price which makes other users buy more to rise the price further. The reverse process is the same.

**Comment by holiman** [comment]
Tests against the actual solidity code : 
https://github.com/bancorprotocol/contracts/blob/master/solidity/hypothesis/test.py#L96

Since executing over TestRPC is a bit slow, there are two separate python re-implementations which have been used to test that exact issue. With the python implementations, it's possible to check millions and millions of randomized test vectors.

**Comment by barakman** [comment]
Just to add to what has already been mentioned above:

1. The exponentiation function (power) always returns a value smaller than or equal to the real value. This can also be proven mathematically, since the Taylor series for e^x converges to this value “from below”. Implementation-wise, the fix-point architecture ensures that there is no rounding, only floor’ing. And since there is no subtraction of a floor’ed value anywhere in the flow of this function, all outcomes (intermediate and final) remain less than or equal to the real (theoretical) outcome.

2. A test for the exponentiation function is available at https://github.com/bancorprotocol/contracts/blob/master/solidity/python/Formula/PowerTest.py. This test can be used both for asserting that the function never returns a value larger than the real value, and for inspecting the average/worst-case accuracy of the function.

3. A test for the sale and purchase forumlae is available at https://github.com/bancorprotocol/contracts/blob/master/solidity/python/FormulaTest.py. This test can be used both for asserting that the corresponding functions never return a value larger than the real value, and for inspecting the average accuracy of each function.

4. In order to keep these tests valid, any change in BancorFormula.sol should be immediately applied into https://github.com/bancorprotocol/contracts/blob/master/solidity/python/Formula/__init__.py and https://github.com/bancorprotocol/contracts/blob/master/solidity/python/Formula/Power/__init__.py.
