### ISSUE TITLE
[Critical Exploit] Price slippage scam

### ISSUE THREAD

**Issue by webcaetano** [bancorprotocol/contracts#194]
### The Exploit

Someone run a bot that is also a ethereum full-node, to get access to tx as soon as possible.
It reads all unconfirmed `tx` that address to a `bancor` contract.
When someone make a `tx` on `bancor` it read and explore the interest `price slippage` percentage.
**And put a tx with higher miner fee, forcing it to go first and profit on the difference price**. 

And sell it right after the `target tx` got confirmed on bancor, realizing the profit.

To fix this the price slippage default should be 1% or even less.
**!! Current default is 5% !!**
Also the user default should be cached. 

Here is one address abusing 
https://etherscan.io/address/0x1d8a5212ae7c196cafbf58ad5f75b7ac9bdeb0b9#tokentxns

As you can see, multiple people per day are falling on this.
Only today this address did that ~25 times and counting

Here a example of this: 
![untitled-1](https://user-images.githubusercontent.com/2578320/36763844-8ce13080-1c08-11e8-8e5f-a88f60a6da51.png)

The User Tx
https://etherscan.io/tx/0x40017c6dab40e1ba9cb41a9391da3d36c28b14bd63206b3f7e2e782f534dd921
The scam Buy right before the User Tx
https://etherscan.io/tx/0xaa094f3e481d37150afd29642856e063f592654583933428f5dd203680a0a6c0
The scam Sell after 
https://etherscan.io/tx/0x256adb60e45b4022338efb3378d9ac9f2f475f6ae8baba83e0b1d13b5261a8ea

I saw multiple people falling on this. With obscene profit going to the bug-exploit.

I tagged that as a critical because, new users have a high chance in fall on this, and give up on bancor. 

Please feel free to delete this issue if you find it compromising.

**Comment by yudilevi** [comment]
@webcaetano hey man - thanks a bunch for that info :)
This is actually a known issue that has been discussed extensively in the past.

We're trying to find the right balance between frontrunning protection on one hand, and giving enough room for a transaction in case the price has changed until that transaction takes place.

We've noticed that when the slippage is defined as 0.5%, many valid transactions fail simply because it takes them time to actually be mined and during that time, other (valid) transactions get in.

So the right number isn't obvious just yet.
We're going to change the number again soon and see how it affects the transactions, I guess it will require a bit of trial & error to get to the right number.

**Comment by webcaetano** [comment]
@yudilevi Good to know. 
Thank you so much.

**Comment by webcaetano** [comment]
@yudilevi reopened 

This is back to happen. Even on `quickConvertPrioritized`

Looks like the scam now consist in having a `bot-alert` for `pending-tx`.
And try to get a fee decimals ahead of the target `tx` 
E.g.
If target fee `50.2` gwei he need to find from the site a fee of `51` gwei

Here's one address abusing:
https://etherscan.io/address/0xa7fa324d0409299566f00e5376825214163589e1#tokentxns

**Comment by yudilevi** [comment]
Hey, thanks for reaching out :)
We're aware of that issue and we're monitoring it.
So far it's not severe like previous attacks so that's the "good" news.

We're debating different approaches - will update of course.

**Comment by webcaetano** [comment]
@yudilevi sure, thank you once again.
