### ISSUE TITLE
Any doc about in-EVM price discovery

### ISSUE THREAD

**Issue by k06a** [bancorprotocol/contracts#202]
Is there any documentation how my smart contract can discover token prices?

**Comment by k06a** [comment]
@yudilevi thanks!

**Comment by yudilevi** [comment]
You will need to add connectors to that converter - tokens that you want to allow the smart token to be convertible against.
You will also need to deposit balance in each of them.

**Comment by k06a** [comment]
@yudilevi I wanna be able to get prices of currently added to Bancor tokes.

**Comment by yudilevi** [comment]
Remember that Bancor is a network of tokens (graph actually) which is composed of many different converter contracts that work together.
To get the conversion price on chain, you'll need to access a specific converter that has the tokens that you're interested connected to it.
Getting a price between any token on the network to any other token can currently only be achieved  through our server APIs since it requires more processing than we care to put on chain.

**Comment by k06a** [comment]
@yudilevi why there is no any kind of facade for Bancor Network contracts? I need to fetch token prices to ETH.

**Comment by yudilevi** [comment]
We're actually working on an on-chain one these days but it's a work in progress.
The main reason it's not there yet is that it requires extra computations (figure out how the balances change with each 'hop' on a path in the token graph) that are simply not needed for the network to function.
But it's a nice feature that will make life easier for some contract developers, so we'd like to add that functionality.

**Comment by yudilevi** [comment]
Yup, on our todo list :)

**Comment by yudilevi** [comment]
@k06a This is now done, see `getReturnByPath`.

**Comment by k06a** [comment]
Awesome @yudilevi!

**Comment by k06a** [comment]
@yudilevi, when new contract with this method will be deployed?

**Comment by yudilevi** [comment]
We're making a few more changes to the contracts these days so I expect it to go live in about 2 weeks or so.

**Comment by k06a** [comment]
@yudilevi found and fixed bug in your current implementation: https://github.com/bancorprotocol/contracts/pull/281
