### ISSUE TITLE
Power function in bancor formula doesn't work when N/D < 1

### ISSUE THREAD

**Issue by nahuseyoum** [bancorprotocol/contracts#222]
Using "power" function when numerator/denominator is > 0 and < 1 doesn't return the correct value. example: power(10, 20, 2, 4) or power(10, 20, 4, 2).

The tests in https://github.com/bancorprotocol/contracts/blob/master/solidity/test/BancorFormula.js do not check if the result is correct either.

**Comment by barakman** [comment]
@nahuseyoum:

This function is neither designated nor used with base values smaller than 1.

Not designated, because (as documented in the code) instead of calculating `base ^ exp`, we calculate `e ^ (log(base) * exp)`.
And `base < 1` ==> `log(base) < 0`, which is of course very difficult (or even impossible) to handle in our "purely unsigned" code.

Not used, because each one of its caller (functions `calculatePurchaseReturn`, `calculateSaleReturn` and `calculateCrossConnectorReturn`, which implement the formulas from Bancor's white-paper), use it with base values larger than 1.

Thanks
